### ISSUE TITLE
Allow webhook creation via API

### ISSUE THREAD

**Issue by ananth-racherla** [muxinc/mux-node-sdk#12] opened 2018-09-18 14:19 UTC
Any chance you could support creation of a Webhook via a new API given client id & secret?

Or perhaps an API to verify that a webhook exists for the given client?

**Comment by jsanford8** [comment] 2018-09-19 15:29
Hey @ananth-racherla - this is a great idea, but at this time we haven't made these management APIs public within our API. We certainly want to, and will in the future, but there's some work we need to do on our backend before we can support this feature at the Node SDK level.

We'll update this issue as we make progress with this issue, but at this time the only way to create/manage webhooks is through our dashboard UI at https://dashboard.mux.com.

**Comment by mmcc** [comment] 2018-12-23 19:07
Just a note, this has recently come up for me a few times as well. We'll revisit this again at the beginning of next year.

**Comment by iamvajid** [comment] 2021-02-21 01:11
Any news here ?

**Comment by dylanjha** [comment] 2021-02-22 19:43
@iamvajid no updates on this yet

**Comment by cwqt** [comment] 2021-06-13 21:25
Was really hoping for this to enable us to use Mux in our terraform setup...

**Comment by michielswaanen** [comment] 2021-08-05 07:32
Any updates so far? Would be a really helpful feature

**Comment by aminamos** [comment] 2021-08-05 21:03
@michielswaanen there are currently no updates on this feature

**Comment by dylanjha** [comment] 2024-02-12 20:08
This is a feature request for Mux the platform, not specific to this SDK so I'm going to go ahead and close this. I very much would still like to see the Mux platforms support this and I've brought this up again with our internal teams.

**Closed by dylanjha** 2024-02-12 20:08 UTC
Labels: enhancement

**Comment by cwqt** [comment] 2024-02-13 12:08
I've long since moved from using MUX, but this response after 6 years isn't that great, the issue is still so open I don't understand why it's being pushed under the rug - implement it in your internal systems, then in the JS SDK, _then_ close the issue as completed.

**Comment by mmcc** [comment] 2024-02-13 19:39
I totally agree that taking 6 years to close this was a bad look, that's on us. This one also kills me because I personally desperately want the functionality in our API, but unfortunately it's just not on any short-to-mid-term roadmap. 

Unfortunately there's no issue or bug here from the SDK's perspective, it's correctly reflecting [the features of the API](https://docs.mux.com/api-reference). Semantically you're right, though, this one should probably have been closed as "not planned" instead of "completed"?

**Comment by dylanjha** [comment] 2024-02-14 03:54
Adjusting the closed status to "not planned" to more accurately reflect that it was not resolved/completed at this time.

The feature itself is still very much something we want to do, and when the Mux API does support this at some time in the future, then we can add it to the SDK.
