### ISSUE TITLE
Direct Upload response changed without notice

### ISSUE THREAD

**Issue by michielswaanen** [muxinc/mux-node-sdk#130] opened 2021-09-06 07:31 UTC
So out of the blue, the structure of the response got updated for the direct upload endpoint.
No type changes are pushed or warnings were given. So I'm not sure if this change was intentional ?

The response object went from `data: {...}` to `data: data: {...}` on the direct upload endpoint.

![image](https://user-images.githubusercontent.com/32015956/132176731-7441d02b-e510-465f-9cf6-9b084c16b588.png)

**Comment by michielswaanen** [comment] 2021-09-06 07:32
We currently implemented a quick fix to make our service available again.

**Comment by dylanjha** [comment] 2021-09-06 07:41
Hi @michielswaanen  -- hmm, can you elaborate or provide more details on the code that is producing this behavior that you're seeing? I'm unable to replicate with the following code:

```js
const Mux = require('@mux/mux-node')
const { Video } = new Mux()
Video.Uploads.create({ new_asset_settings: { playback_policy: 'public' }, }).then(console.log)

/*
> {
  url: 'https://storage.googleapis.com/video-storage-us-east1-uploads/wyZjGJM6m1G3MUvG001wI67oxPG028N9nU?Expires=1630917438&GoogleAccess',
  timeout: 3600,
  status: 'waiting',
  new_asset_settings: { playback_policies: [ 'public' ] },
  id: 'wyZjGJM6m1G3MUvG001wI67oxPG028N9nU'
}
*/
```

I tried both with a slightly older version of this package (3.1.0) and the most recent (3.2.0) -- I'm seeing the intended behavior:

<img width="861" alt="mux-node-3-2-3_2021-09-06_00-37-29" src="https://user-images.githubusercontent.com/764988/132178682-51de0cf2-ab0c-4b02-b380-3e532e8f8a27.png">

**Comment by michielswaanen** [comment] 2021-09-06 07:56
This is our code snippet @dylanjha 

```typescript
const upload = await this.mux.Video.Uploads.create({
    new_asset_settings: {
      playback_policy: 'public',
      passthrough: recording.id,
    },
    timeout: String(60),
    cors_origin: new MuxConfig().load().corsOrigin,
    test: new MuxConfig().load().test,
});

console.log(upload);
```

```
[server-local] {
[server-local]   status: 201,
[server-local]   statusText: 'Created',
[server-local]   headers: {
[server-local]     'cache-control': 'max-age=0, private, must-revalidate',
[server-local]     'content-length': '934',
[server-local]     'content-type': 'application/json; charset=utf-8',
[server-local]     date: 'Mon, 06 Sep 2021 07:52:26 GMT',
[server-local]     server: 'Mux API Server v1.128.10',
[server-local]     'x-request-id': 'FqIsUkTShYmjIvsGtQgD',
[server-local]     connection: 'close'
[server-local]   },
[server-local]   config: {
[server-local]     url: '/video/v1/uploads',
[server-local]     method: 'post',
[server-local]     data: '{"new_asset_settings":{"playback_policy":"public","passthrough":"f3012119-4c21-4777-a17a-ef27b017282e"},"timeout":"60","cors_origin":"app.stadro.localhost","test":false}',
[server-local]     headers: {
[server-local]       Accept: 'application/json',
[server-local]       'Content-Type': 'application/json',
[server-local]       'User-Agent': 'Mux Node | 3.2.3',
[server-local]       'Content-Length': 169
[server-local]     },
[server-local]     auth: {
[server-local]       username: 'xxx',
[server-local]       password: 'xxx'
[server-local]     },
[server-local]     baseURL: 'https://api.mux.com',
[server-local]     transformRequest: [ [Function: transformRequest] ],
[server-local]     transformResponse: [ [Function: transformResponse] ],
[server-local]     timeout: 0,
[server-local]     withCredentials: false,
[server-local]     adapter: [Function: httpAdapter],
[server-local]     xsrfCookieName: 'XSRF-TOKEN',
[server-local]     xsrfHeaderName: 'X-XSRF-TOKEN',
[server-local]     maxContentLength: -1,
[server-local]     maxBodyLength: -1,
[server-local]     validateStatus: [Function: validateStatus],
[server-local]     transitional: {
[server-local]       silentJSONParsing: true,
[server-local]       forcedJSONParsing: true,
[server-local]       clarifyTimeoutError: false
[server-local]     },
[server-local]     mode: 'cors'
[server-local]   },
[server-local]   request: <ref *1> ClientRequest {
[server-local]     _events: [Object: null prototype] {
[server-local]       abort: [Function (anonymous)],
[server-local]       aborted: [Function (anonymous)],
[server-local]       connect: [Function (anonymous)],
[server-local]       error: [Function (anonymous)],
[server-local]       socket: [Function (anonymous)],
[server-local]       timeout: [Function (anonymous)],
[server-local]       prefinish: [Function: requestOnPrefinish]
[server-local]     },
[server-local]     _eventsCount: 7,
[server-local]     _maxListeners: undefined,
[server-local]     outputData: [],
[server-local]     outputSize: 0,
[server-local]     writable: true,
[server-local]     destroyed: false,
[server-local]     _last: true,
[server-local]     chunkedEncoding: false,
[server-local]     shouldKeepAlive: false,
[server-local]     _defaultKeepAlive: true,
[server-local]     useChunkedEncodingByDefault: true,
[server-local]     sendDate: false,
[server-local]     _removedConnection: false,
[server-local]     _removedContLen: false,
[server-local]     _removedTE: false,
[server-local]     _contentLength: null,
[server-local]     _hasBody: true,
[server-local]     _trailer: '',
[server-local]     finished: true,
[server-local]     _headerSent: true,
[server-local]     _closed: false,
[server-local]     socket: TLSSocket {
[server-local]       _tlsOptions: [Object],
[server-local]       _secureEstablished: true,
[server-local]       _securePending: false,
[server-local]       _newSessionPending: false,
[server-local]       _controlReleased: true,
[server-local]       secureConnecting: false,
[server-local]       _SNICallback: null,
[server-local]       servername: 'api.mux.com',
[server-local]       alpnProtocol: false,
[server-local]       authorized: true,
[server-local]       authorizationError: null,
[server-local]       encrypted: true,
[server-local]       _events: [Object: null prototype],
[server-local]       _eventsCount: 10,
[server-local]       connecting: false,
[server-local]       _hadError: false,
[server-local]       _parent: null,
[server-local]       _host: 'api.mux.com',
[server-local]       _readableState: [ReadableState],
[server-local]       _maxListeners: undefined,
[server-local]       _writableState: [WritableState],
[server-local]       allowHalfOpen: false,
[server-local]       _sockname: null,
[server-local]       _pendingData: null,
[server-local]       _pendingEncoding: '',
[server-local]       server: undefined,
[server-local]       _server: null,
[server-local]       ssl: [TLSWrap],
[server-local]       _requestCert: true,
[server-local]       _rejectUnauthorized: true,
[server-local]       parser: null,
[server-local]       _httpMessage: [Circular *1],
[server-local]       [Symbol(res)]: [TLSWrap],
[server-local]       [Symbol(verified)]: true,
[server-local]       [Symbol(pendingSession)]: null,
[server-local]       [Symbol(async_id_symbol)]: 2258,
[server-local]       [Symbol(kHandle)]: [TLSWrap],
[server-local]       [Symbol(kSetNoDelay)]: false,
[server-local]       [Symbol(lastWriteQueueSize)]: 0,
[server-local]       [Symbol(timeout)]: null,
[server-local]       [Symbol(kBuffer)]: null,
[server-local]       [Symbol(kBufferCb)]: null,
[server-local]       [Symbol(kBufferGen)]: null,
[server-local]       [Symbol(kCapture)]: false,
[server-local]       [Symbol(kBytesRead)]: 0,
[server-local]       [Symbol(kBytesWritten)]: 0,
[server-local]       [Symbol(connect-options)]: [Object],
[server-local]       [Symbol(RequestTimeout)]: undefined
[server-local]     },
[server-local]     _header: 'POST /video/v1/uploads HTTP/1.1\r\n' +
[server-local]       'Accept: application/json\r\n' +
[server-local]       'Content-Type: application/json\r\n' +
[server-local]       'User-Agent: Mux Node | 3.2.3\r\n' +
[server-local]       'Content-Length: 169\r\n' +
[server-local]       'Host: api.mux.com\r\n' +
[server-local]       'Authorization: Basic xxxx' +
[server-local]       'Connection: close\r\n' +
[server-local]       '\r\n',
[server-local]     _keepAliveTimeout: 0,
[server-local]     _onPendingData: [Function: nop],
[server-local]     agent: Agent {
[server-local]       _events: [Object: null prototype],
[server-local]       _eventsCount: 2,
[server-local]       _maxListeners: undefined,
[server-local]       defaultPort: 443,
[server-local]       protocol: 'https:',
[server-local]       options: [Object: null prototype],
[server-local]       requests: [Object: null prototype] {},
[server-local]       sockets: [Object: null prototype],
[server-local]       freeSockets: [Object: null prototype] {},
[server-local]       keepAliveMsecs: 1000,
[server-local]       keepAlive: false,
[server-local]       maxSockets: Infinity,
[server-local]       maxFreeSockets: 256,
[server-local]       scheduling: 'lifo',
[server-local]       maxTotalSockets: Infinity,
[server-local]       totalSocketCount: 1,
[server-local]       maxCachedSessions: 100,
[server-local]       _sessionCache: [Object],
[server-local]       [Symbol(kCapture)]: false
[server-local]     },
[server-local]     socketPath: undefined,
[server-local]     method: 'POST',
[server-local]     maxHeaderSize: undefined,
[server-local]     insecureHTTPParser: undefined,
[server-local]     path: '/video/v1/uploads',
[server-local]     _ended: true,
[server-local]     res: IncomingMessage {
[server-local]       _readableState: [ReadableState],
[server-local]       _events: [Object: null prototype],
[server-local]       _eventsCount: 3,
[server-local]       _maxListeners: undefined,
[server-local]       socket: [TLSSocket],
[server-local]       httpVersionMajor: 1,
[server-local]       httpVersionMinor: 1,
[server-local]       httpVersion: '1.1',
[server-local]       complete: true,
[server-local]       rawHeaders: [Array],
[server-local]       rawTrailers: [],
[server-local]       aborted: false,
[server-local]       upgrade: false,
[server-local]       url: '',
[server-local]       method: null,
[server-local]       statusCode: 201,
[server-local]       statusMessage: 'Created',
[server-local]       client: [TLSSocket],
[server-local]       _consuming: true,
[server-local]       _dumped: false,
[server-local]       req: [Circular *1],
[server-local]       responseUrl: 'https://e5c2a4d0-b130-450d-8286-b94b279bb63c:OlpmpkjvXXXXXXDMheWI1VG4jeZ5zV17IRJ8%2FiYefq2WApcZv1zjZuGYI%2ByFi3fYGZlMdNaX0GPBOsBS@api.mux.com/video/v1/uploads',
[server-local]       redirects: [],
[server-local]       [Symbol(kCapture)]: false,
[server-local]       [Symbol(kHeaders)]: [Object],
[server-local]       [Symbol(kHeadersCount)]: 14,
[server-local]       [Symbol(kTrailers)]: null,
[server-local]       [Symbol(kTrailersCount)]: 0,
[server-local]       [Symbol(RequestTimeout)]: undefined
[server-local]     },
[server-local]     aborted: false,
[server-local]     timeoutCb: null,
[server-local]     upgradeOrConnect: false,
[server-local]     parser: null,
[server-local]     maxHeadersCount: null,
[server-local]     reusedSocket: false,
[server-local]     host: 'api.mux.com',
[server-local]     protocol: 'https:',
[server-local]     _redirectable: Writable {
[server-local]       _writableState: [WritableState],
[server-local]       _events: [Object: null prototype],
[server-local]       _eventsCount: 2,
[server-local]       _maxListeners: undefined,
[server-local]       _options: [Object],
[server-local]       _ended: true,
[server-local]       _ending: true,
[server-local]       _redirectCount: 0,
[server-local]       _redirects: [],
[server-local]       _requestBodyLength: 169,
[server-local]       _requestBodyBuffers: [],
[server-local]       _onNativeResponse: [Function (anonymous)],
[server-local]       _currentRequest: [Circular *1],
[server-local]       _currentUrl: 'https://e5c2a4d0-b130-450d-8286-b94b279bb63c:OlpmpkjvXXXXXheWI1VG4jeZ5zV17IRJ8%2FiYefq2WApcZv1zjZuGYI%2ByFi3fYGZlMdNaX0GPBOsBS@api.mux.com/video/v1/uploads',
[server-local]       [Symbol(kCapture)]: false
[server-local]     },
[server-local]     [Symbol(kCapture)]: false,
[server-local]     [Symbol(kNeedDrain)]: false,
[server-local]     [Symbol(corked)]: 0,
[server-local]     [Symbol(kOutHeaders)]: [Object: null prototype] {
[server-local]       accept: [Array],
[server-local]       'content-type': [Array],
[server-local]       'user-agent': [Array],
[server-local]       'content-length': [Array],
[server-local]       host: [Array],
[server-local]       authorization: [Array]
[server-local]     }
[server-local]   },
[server-local]   data: {
[server-local]     data: {
[server-local]       url: 'https://storage.googleapis.com/video-storage-us-east1-uploads/gxd51X4JBxdHON6pu3xOtNu7xW0XXXXXXXGR202BLCvU?Expires=1630914806&GoogleAccessId=direct-uploads-writer-prod%40mux-cloud.iam.gserviceaccount.com&Signature=J3hHlF2UKLAglS8Zdc5OkadDlDwTDoXH6%2FOYxYaNmGvUJLDwLvCZKvAEV%2Fhgmtv95Dcu9hKYpkNrTH4O1v0PYM6KUfmtmERVy2Oz7%2BjIZ6IfZs0gUcOJRT6clcFng2qCoOb72Kl0zdAc0gEgimESKONoYBFY0ioGbEWSYl9xjHrhOiCE1m5va4b9oFN2ej%2Bx5pviE6VlBtPp%2Bk9duk%2FWhzBRKevlTsM0oqtH7kAAxYqMnH1mnaMS0FS1fVMWJcWyvVbiB4GgiGgqXtIPbhF85dgcypIuPLVRCXqpfmTZv4Ua7SS7QeNPKLd%2FL0nZozgjCGI9Ty7DqF3VsZrVu0ReDA%3D%3D&upload_id=ADPycdvBr_daFrkeGdrtYKXmjSqlt4FxPgbpnY67363hQy7tdiOgmoKMsGJt8VJ9iDQlEIUP8z-BS4XC84tw1HLADbbJrsV1VA',
[server-local]       timeout: 60,
[server-local]       status: 'waiting',
[server-local]       new_asset_settings: [Object],
[server-local]       id: 'gxd51X4JBxdHON6pu3xOtNu7xW00AXxyyDVGR202BLCvU',
[server-local]       cors_origin: 'app.stadro.localhost'
[server-local]     }
[server-local]   }
[server-local] }
```

**Comment by michielswaanen** [comment] 2021-09-06 07:57
We're running on version `"@mux/mux-node": "^3.1.4`

**Comment by dylanjha** [comment] 2021-09-06 08:51
@michielswaanen can you run this script and copy/paste the output?

https://gist.github.com/dylanjha/30f07784a4e646008a2898b0ece9ed96

The output should look something like this (version gets logged and then the response from `Video.Uploads.create` gets logged:

```
❯ MUX_TOKEN_ID=xxxxx MUX_TOKEN_SECRET=xxxx node ./mux-create-upload.js
Version 3.1.4
{
  url: 'https://storage.googleapis.com/vid...',
  timeout: 3600,
  status: 'waiting',
  new_asset_settings: { playback_policies: [ 'public' ] },
  id: 'B5vvTQGJEyTJF01PotY00FOYkprwu2XAMs'
}

```

I'm very curious if you could run that script above and if you're still getting the same output.

What you're logging there looks like the full axios response. The only place that I know of where we expose that is the `request` and  `response` [events that fire async](https://github.com/muxinc/mux-node-sdk#request-and-response-events) -- do you happen to have any of those listeners set up?

**Comment by michielswaanen** [comment] 2021-09-06 09:04
Your script runs fine and return the expected output. We're currently investigating what is going wrong at our side.

**Comment by michielswaanen** [comment] 2021-09-06 09:26
For the record, we've no listeners set up that would log the request itself. We're trying out a higher version of Mux now.

**Comment by dylanjha** [comment] 2021-09-06 14:33
@michielswaanen interesting. It _shouldn't_ be a versioning thing, as this behavior never changed and you can see I ran this with 3.1.4

Let me know what you find

**Comment by dylanjha** [comment] 2021-09-06 15:06
@michielswaanen I suspect that somehow the underlying axios instance is being modified in a way that bypasses our response interceptor?

I don't know how one would do that, esp while also preserving the axios instance in a way so the authentication still gets passed through.

Are you doing anything in your node environment that might point in that direction?

**Comment by dylanjha** [comment] 2021-09-07 16:46
@michielswaanen I'm going to go ahead and close this since it looks this this is something really specific to the node environment where this is running.

If any more information becomes available, or there's something mux-node can do to help -- please let us know.

**Closed by dylanjha** 2021-09-07 16:46 UTC

**Comment by dylanjha** [comment] 2021-09-20 16:53
Fixed in https://github.com/muxinc/mux-node-sdk/releases/tag/v3.3.1
