### ISSUE TITLE
Best practices for tracking duplicate webhooks

### ISSUE THREAD

**Issue by cwqt** [muxinc/mux-node-sdk#83] opened 2020-12-14 13:36 UTC
I was wondering if there's an accepted way to handle duplicate hooks, currently I'm hashing the response data & storing that in Redis & checking against it to see if I've already handled a hook.

I'm just confused as there seems to be no identifier to say "these hooks were meant to do this action on this object" that we can use to check for duplicates, since each webhook/attempt has a unique identifier.

e.g. a `video.asset.errored` has happened twice in the same day on the same object - so they're not duplicate hooks, but have duplicate data. Maybe I'm missing something here - thanks in advance for any pointers.

**Comment by dylanjha** [comment] 2020-12-14 18:39
Hi @cwqt , thanks for reaching out. It sounds like there might be a little confusion.

First off, if your server responds with a non-2xx response, then Mux will re-try the same hook (this will be reflected in the `attempts` key in the request body.

But it sounds like that's not what you're running into. When an asset errors, the `video.asset.errored` *event* should only happen once on a particular asset (on the asset page in the Mux dashboard you should see something like this):

<img width="826" alt="errored_2020-12-14_10-33-31" src="https://user-images.githubusercontent.com/764988/102121100-4690a380-3df8-11eb-8c41-968a4dc56e06.png">

In the dashboard, if you're seeing multiple `video.asset.errored` *events* on the asset then please surface that through support channels so that we can investigate.

If you click into the `video.asset.errored` even then you'll see details for that event, including webhook delivery attempts. Make sure: (1) your server is responding with 2xx on webhooks and (2) you only have one webhook endpoint configured.

In any case, if you email help@mux.com or use the intercom chat bubble in the web application we'd be happy to take a closer look at your account and help you figure out what's going on.

**Comment by cwqt** [comment] 2020-12-14 19:33
> But it sounds like that's not what you're running into. When an asset errors, the video.asset.errored event should only happen once on a particular asset (on the asset page in the Mux dashboard you should see something like this):

Ah think I confused you with my bad example - I don't have any issue with errors, maybe I can clarify a bit more.
The MUX docs say:

> Note: Mux makes an effort to deliver each message successfully once, but in certain situations duplicate webhook messages may be sent even if your service responds with a 2xx response code.

If a previously successfully handled webhook is fired again on accident, does its attempts include that successful attempt?

I guess what I'm asking if there is a way to 'group' webhooks by intention of action without depending on the attempts array in order to 100% ignore duplicates / misfires.

**Comment by dylanjha** [comment] 2020-12-15 04:40
Got it, thanks for clarifying @cwqt. Duplicate webhook delivery should be incredibly rare. Is this something you are seeing systematically or in an easily reproducible way?

In this case, the top level `id` in the request body should be the same. This should help clarify what's going on:

- In Mux's world there is an **event** that happens.
- events have a `type` (for example: `video.asset.ready`, `video.asset.errored`, `video.live_stream.created`, etc.)
- events also correspond to an object (an `asset` or `live_stream` for example)
- events have a unique `id`. Note that there is an `id` associated with the event itself, and there is a different `id` associated with the object that the event corresponds to
- Every time an event happens, Mux sends webhook notifications to any configured webhook endpoints

If duplicate webhook notifications are sent for an event (again, this should be incredibly rare), the event's `id` should be the same in both request bodies.

I appreciate you raising this for visibility, but since this is more of a support issue and not something specific to this node SDK I'm going to go ahead and close this issue and I would like to redirect this conversation to Mux support channels (please email help@mux.com or use the intercom chat bubble in the web application so we can provide more specific support for your use case and debug specific examples related to your account).

Thanks for reaching out @cwqt !

**Closed by dylanjha** 2020-12-15 04:40 UTC

**Comment by cwqt** [comment] 2020-12-15 11:09
Appreciate the write-up, but I think this is an important issue that shouldn't be sidelined into support channels, especially when money is on the line depending on if a hook is accidentally re-handled.

> If duplicate webhook notifications are sent for an event (again, this should be incredibly rare), **the event's `id` should be the same in both request bodies.**

Right okay, that's just not made clear in the documentation, it's really ambiguous that & not clear that duplicate webhooks (not a re-attempt) will have the same Id, even now you say they _should_, not they _will_ ...

**Comment by dylanjha** [comment] 2020-12-16 04:21
Hi @cwqt I agree it's an important issue.  We just try to keep the issues in this repo specific to the node SDK.

I double checked this functionality, duplicates and re-attempts will have the same top level `id` (which is a unique identifier for the event). Thanks for the docs feedback, we can definitely make that more clear, thank you!
